// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Prodotto.EF.Entity
{
    [Keyless]
    [Table("comuni")]
    public partial class Comuni
    {
        [Column("id")]
        public int Id { get; set; }
        [Column("id_regione")]
        public int IdRegione { get; set; }
        [Column("id_provincia")]
        public int IdProvincia { get; set; }
        [Required]
        [Column("comune")]
        [StringLength(100)]
        public string Comune { get; set; }
    }
}