// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Prodotto.EF.Entity
{
    [Keyless]
    public partial class Movimenti
    {
        [Required]
        [Column("ID")]
        [StringLength(10)]
        public string Id { get; set; }
        [Column("NumCONFORD")]
        [StringLength(10)]
        public string NumConford { get; set; }
        [Column("NumDDT")]
        [StringLength(10)]
        public string NumDdt { get; set; }
        [Column("NumFAT")]
        [StringLength(10)]
        public string NumFat { get; set; }
    }
}