// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Prodotto.EF.Entity
{
    [Keyless]
    [Table("Order Subtotals")]
    public partial class OrderSubtotals
    {
        [Column("OrderID")]
        public int OrderId { get; set; }
        [Column(TypeName = "smallmoney")]
        public decimal? Subtotal { get; set; }
    }
}