// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Prodotto.EF.Entity
{
    [Keyless]
    [Table("province")]
    public partial class Province
    {
        [Column("id")]
        public int Id { get; set; }
        [Column("id_regione")]
        public int IdRegione { get; set; }
        [Required]
        [Column("provincia")]
        [StringLength(100)]
        public string Provincia { get; set; }
        [Required]
        [Column("sigla")]
        [StringLength(2)]
        public string Sigla { get; set; }
    }
}