// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Prodotto.EF.Entity
{
    [Keyless]
    [Table("RegistriIVA")]
    public partial class RegistriIva
    {
        [Required]
        [Column("ID")]
        [StringLength(5)]
        public string Id { get; set; }
        [StringLength(50)]
        public string Descrizione { get; set; }
        [StringLength(5)]
        public string Tipo { get; set; }
    }
}