// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Prodotto.EF.Entity
{
    [Keyless]
    [Table("regioni")]
    public partial class Regioni
    {
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("regione")]
        [StringLength(100)]
        public string Regione { get; set; }
    }
}